"""school id to give

Revision ID: 28b525ef024b
Revises: 832aeef82ba4
Create Date: 2022-06-10 00:24:03.006079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b525ef024b'
down_revision = '832aeef82ba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('group')

    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
