"""fix model teacher

Revision ID: 3bfae8821d3b
Revises: 6cc0bb73137e
Create Date: 2022-06-21 02:05:01.341820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfae8821d3b'
down_revision = '6cc0bb73137e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
