"""added classes

Revision ID: 4e752574d69e
Revises: a3337f7b217b
Create Date: 2022-06-29 11:07:44.129015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e752574d69e'
down_revision = 'a3337f7b217b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_db_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_class_school', 'schools', ['school_db_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_class_school', type_='foreignkey')
        batch_op.drop_column('school_db_id')

    # ### end Alembic commands ###
