"""added relationship school_group

Revision ID: 6cc0bb73137e
Revises: 43b2e8f66bea
Create Date: 2022-06-17 12:21:18.114672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc0bb73137e'
down_revision = '43b2e8f66bea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_db_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_groups_school_id', 'schools', ['school_db_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_groups_school_id', type_='foreignkey')
        batch_op.drop_column('school_db_id')

    # ### end Alembic commands ###
