"""deleted school_name from group

Revision ID: 7dcd49db1f8d
Revises: d2a0980b9a49
Create Date: 2022-07-21 22:30:50.642723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcd49db1f8d'
down_revision = 'd2a0980b9a49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
