"""added keymodel

Revision ID: 832aeef82ba4
Revises: 8fb3fa5332db
Create Date: 2022-06-09 10:39:04.056337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832aeef82ba4'
down_revision = '8fb3fa5332db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys')
    # ### end Alembic commands ###
