"""added relationship school-group

Revision ID: 8a6182fec94f
Revises: 43b2e8f66bea
Create Date: 2022-06-17 12:12:38.809913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6182fec94f'
down_revision = '43b2e8f66bea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_students_school_id', 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_school_id', type_='foreignkey')

    # ### end Alembic commands ###
