"""added teacher relationship

Revision ID: a3337f7b217b
Revises: 5b1a02db2a61
Create Date: 2022-06-29 01:05:37.640145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3337f7b217b'
down_revision = '5b1a02db2a61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_db_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_teacher_school', 'schools', ['school_db_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teacher_school', type_='foreignkey')
        batch_op.drop_column('school_db_id')

    # ### end Alembic commands ###
