"""added day and scheduleclass

Revision ID: a9e926df9570
Revises: 4e752574d69e
Create Date: 2022-07-01 00:54:44.728636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e926df9570'
down_revision = '4e752574d69e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduleclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduleclasses')
    op.drop_table('days')
    # ### end Alembic commands ###
