"""added relationship group-day

Revision ID: bc485f9cd8b0
Revises: a9e926df9570
Create Date: 2022-07-01 01:01:23.430504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc485f9cd8b0'
down_revision = 'a9e926df9570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_day_group', 'groups', ['group_id'], ['id'])
        batch_op.drop_column('group')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_day_group', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
