"""telegram permitions

Revision ID: bd4160977c51
Revises: f0f96c93dd3a
Create Date: 2022-09-09 12:09:35.136037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4160977c51'
down_revision = 'f0f96c93dd3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    with op.batch_alter_table('telegram_autorizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hw', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('diary_id', sa.Integer(), nullable=True))
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_autorizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('hw')
        batch_op.drop_column('mark')

    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
