"""added id to group

Revision ID: beebd8638b3a
Revises: 3d47b2782ab8
Create Date: 2022-06-13 01:04:33.579670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beebd8638b3a'
down_revision = '3d47b2782ab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer()))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
