"""added subject relationship

Revision ID: c115c177c15d
Revises: 3bfae8821d3b
Create Date: 2022-06-28 23:47:33.462794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c115c177c15d'
down_revision = '3bfae8821d3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_db_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subject_school', 'schools', ['school_db_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subject_school', type_='foreignkey')
        batch_op.drop_column('school_db_id')

    # ### end Alembic commands ###
