"""deleted days

Revision ID: c380f9622fcc
Revises: bbc01ffeca65
Create Date: 2022-07-22 01:43:13.362492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c380f9622fcc'
down_revision = 'bbc01ffeca65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduleclasses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_class_day', type_='foreignkey')
        batch_op.create_foreign_key('fk_class_group', 'groups', ['group_id'], ['id'])
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduleclasses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_class_group', type_='foreignkey')
        batch_op.create_foreign_key('fk_class_day', 'days', ['day_id'], ['id'])
        batch_op.drop_column('group_id')
        batch_op.drop_column('day_number')

    # ### end Alembic commands ###
