"""telegram

Revision ID: f0f96c93dd3a
Revises: 19291fc816ee
Create Date: 2022-09-08 15:01:36.822390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f96c93dd3a'
down_revision = '19291fc816ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_autorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_number', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_day_group'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('telegram_autorizations')
    # ### end Alembic commands ###
