"""mark edit

Revision ID: f702ddf59ed4
Revises: bd4160977c51
Create Date: 2022-09-15 12:57:00.995783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f702ddf59ed4'
down_revision = 'bd4160977c51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('season', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('season')
        batch_op.drop_column('final')

    # ### end Alembic commands ###
